routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home','HomeController@index')->name('home');
//Route::get('/user', 'UserController@index')->name('user');
//Route::get('/admin', 'AdminController@index')->name('admin');



//Route::get('/', function () {
   // return view('shop.index');
//});

Route::get('/', [
    'uses' => 'CartiController@getIndex',
    'as' => 'carti.index'
]);



Route::get('/', [
    'uses' => 'CartiController@getIndex',
    'as' => 'carti.index2'
]);

Route::get('/add-to-cart/{id}', [
    'uses' => 'CartiController@getAddToCart',
    'as' => 'carti.addToCart'
]);


Route::get('/reduce/{id}', [
    'uses' => 'CartiController@getReduceByOne',
    'as'  =>  'carti.reduceByOne'
]);

Route::get('/remove/{id}', [
    'uses' => 'CartiController@getRemoveItem',
    'as' => 'carti.remove'

]);

//Route::post('/userii/{id}', [
  //  'uses' => 'UserController@index',
  //  'as' => 'users.index'

//]);

Route::get('/shopping-cart', [
    'uses' => 'CartiController@getCart',
    'as' => 'carti.shoppingCart'
]);

Route::get('/checkout', [
    'uses' => 'CartiController@getCheckout',
    'as' => 'checkout',
    'middleware' => 'auth'
]);

Route::get('/profile', [
   'uses' => 'UserController@getProfile',
   'as' => 'user.profile'
]);

Route::get('/reports', [
    'uses' => 'CartiController@getReports',
'as' => 'shop.reports'
]);

Route::post('/checkout', [
   'uses' => 'CartiController@postCheckout',
    'as' => 'checkout'
]);

//Route::group(['middleware' => ['auth']], function() {

   // Route::resource('carti','CartiController');
//});

Route::resource('carti','CartiController');

Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles','RoleController');
    Route::resource('userii','UserController');
    Route::resource('carti','CartiController');
});

Route::middleware(['auth'])->group(function () {
    Route::get('/approval', 'HomeController@approval')->name('approval');
    Route::get('/home', 'HomeController@index')->name('home');
});



Route::middleware(['auth'])->group(function () {
    Route::get('/approval', 'HomeController@approval')->name('approval');

    Route::middleware(['approved'])->group(function () {
        Route::get('/home', 'HomeController@index')->name('home');
    });

    Route::middleware(['admin'])->group(function () {
        Route::get('/users', 'UserController@index2')->name('admin.users.index');
        Route::get('/users/{user_id}/approve', 'UserController@approve')->name('admin.users.approve');
    });
});

resources/views/partials/header.blade.php
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>



    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{{route('carti.index2')}}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{route('carti.shoppingCart')}}">Book Cart
                <span class="badge">{{Session::has('cartitem') ? Session::get('cartitem')->totalCantitati : ''}}</span>
                </a>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    User Actions
                </a>

                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{{'register'}}">Register Account</a>
                    <a class="dropdown-item" href="{{'login'}}">Login && Logout</a>
                    <a class="dropdown-item" href="{{route('user.profile')}}">My Account</a>



                </div>
            </li>




            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Admin Panel
                </a>

                <div class="dropdown-menu" aria-labelledby="navbarDropdown">




                    @if(!Auth::guest())
                        @hasrole("admin")
                        <a class="nav-link" href="{{ route('userii.index') }}">Manage Users</a>
                        <a class="nav-link" href="{{ route('carti.index') }}">Manage Carti</a>
                        <a class="nav-link" href="{{ route('shop.reports') }}">Rapoarte</a>
                        @endhasrole
                    @endif
                    <div class="dropdown-divider"></div>

                </div>
            </li>

        </ul>

    </div>
</nav>