routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home','HomeController@index')->name('home');
//Route::get('/user', 'UserController@index')->name('user');
//Route::get('/admin', 'AdminController@index')->name('admin');



//Route::get('/', function () {
   // return view('shop.index');
//});

Route::get('/', [
    'uses' => 'CartiController@getIndex',
    'as' => 'carti.index'
]);



Route::get('/', [
    'uses' => 'CartiController@getIndex',
    'as' => 'carti.index2'
]);

Route::get('/add-to-cart/{id}', [
    'uses' => 'CartiController@getAddToCart',
    'as' => 'carti.addToCart'
]);


Route::get('/reduce/{id}', [
    'uses' => 'CartiController@getReduceByOne',
    'as'  =>  'carti.reduceByOne'
]);

Route::get('/remove/{id}', [
    'uses' => 'CartiController@getRemoveItem',
    'as' => 'carti.remove'

]);

//Route::post('/userii/{id}', [
  //  'uses' => 'UserController@index',
  //  'as' => 'users.index'

//]);

Route::get('/shopping-cart', [
    'uses' => 'CartiController@getCart',
    'as' => 'carti.shoppingCart'
]);

Route::get('/checkout', [
    'uses' => 'CartiController@getCheckout',
    'as' => 'checkout',
    'middleware' => 'auth'
]);

Route::get('/profile', [
   'uses' => 'UserController@getProfile',
   'as' => 'user.profile'
]);

Route::get('/reports', [
    'uses' => 'CartiController@getReports',
'as' => 'shop.reports'
]);

Route::post('/checkout', [
   'uses' => 'CartiController@postCheckout',
    'as' => 'checkout'
]);

//Route::group(['middleware' => ['auth']], function() {

   // Route::resource('carti','CartiController');
//});

Route::resource('carti','CartiController');

Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles','RoleController');
    Route::resource('userii','UserController');
    Route::resource('carti','CartiController');
});

Route::middleware(['auth'])->group(function () {
    Route::get('/approval', 'HomeController@approval')->name('approval');
    Route::get('/home', 'HomeController@index')->name('home');
});



Route::middleware(['auth'])->group(function () {
    Route::get('/approval', 'HomeController@approval')->name('approval');

    Route::middleware(['approved'])->group(function () {
        Route::get('/home', 'HomeController@index')->name('home');
    });

    Route::middleware(['admin'])->group(function () {
        Route::get('/users', 'UserController@index2')->name('admin.users.index');
        Route::get('/users/{user_id}/approve', 'UserController@approve')->name('admin.users.approve');
    });
});

app/Carti.php
<?php


namespace App;

use Illuminate\Database\Eloquent\Model;

class Carti extends Model
{

    public $table = 'carti';
    protected $fillable = [
        'titlu', 'autor', 'pret','cantitati','imagePath'
    ];


   // public function users(){
   //     return $this->belongsToMany(User::class,'user_carti');
   // }
}

app/Http/Controllers/CartiController.php
<?php

namespace App\Http\Controllers;

use App\CartItem;
use App\Carti;
use App\Order;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Session;


class CartiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Carti[]|\Illuminate\Database\Eloquent\Collection
     */


    public function getIndex(){
        $carti = Carti::all();
        return view('shop.index', ['carti' => $carti]);
    }

    public function getAddToCart(Request $request, $id){
        $carti = Carti::find($id);
        $oldCart = Session::has('cartitem') ? Session::get('cartitem') : null;
        $cartitem = new CartItem($oldCart);
        $cartitem->add($carti, $carti->id);

        $request->session()->put('cartitem', $cartitem );
       // dd($request->session()->get('cartitem'));
        return redirect()->route('carti.index2');



    }

    public function getReduceByOne($id) {
        $oldCart = Session::has('cartitem') ? Session::get('cartitem') : null;
        $cartitem = new CartItem($oldCart);
        $cartitem->reduceByOne($id);

        if(count($cartitem->items)>0)
        {
            Session::put('cartitem', $cartitem);

        }
        else
        {
            Session::forget('cartitem');
        }
        return redirect()->route('carti.shoppingCart');

    }

    public function getRemoveItem($id) {

        $oldCart = Session::has('cartitem') ? Session::get('cartitem') : null;
        $cartitem = new CartItem($oldCart);
        $cartitem->removeItem($id);

        if(count($cartitem->items)>0)
        {
            Session::put('cartitem', $cartitem);

        }
        else
        {
            Session::forget('cartitem');
        }



        return redirect()->route('carti.shoppingCart');


    }


    public function getCart(){
        if(!Session::has('cartitem')){

            return view('shop.shopping-cart');
        }

        $oldCart = Session::get('cartitem');
        $cartitem = new CartItem($oldCart);
        return view('shop.shopping-cart', ['carti' => $cartitem->items, 'totalPrice' => $cartitem->totalPrice]);



    }


    public function getCheckout(){
        if(!Session::has('cartitem')){

            return view('shop.shopping-cart');
        }
        $oldCart = Session::get('cartitem');
        $cartitem = new CartItem($oldCart);
        $total = $cartitem->totalPrice;
        $qty = $cartitem->totalCantitati;
        $titlu= $cartitem->titlu;
        $autor=$cartitem->autor;

        return view('shop.checkout', ['total' => $total],['qty' => $qty]);

        $order= new Order();
        $order->cartitem = serialize($cartitem);
        //$order->address
        Auth::user()->orders()->save($order);



    }



    public function postCheckout(Request $request){

        if(!Session::has('cartitem')){

            return redirect()->route('shop.shoppingCart');
        }
        $oldCart = Session::get('cartitem');
        $cartitem = new CartItem($oldCart);

        $order = new Order();
        $order->cartitem = serialize($cartitem);
        $order->address = $request->input('address');
        $order->name = $request->input('name');
        $order->oras= $request->input('oras');
        $order->cantitati=$request->input('cantitati');
        $order->autor=$request->input('autor');

        Auth::user()->orders()->save($order);

        Session::forget('cartitem');
        return redirect()->route('carti.index2')->with('success', 'Successfully purchased books!');


    }

    public function getReports(Request $request){

        return view ('shop.reports');



    }

   // function __construct()
  //  {
   //     $this->middleware('permission:carti-list|carti-create|carti-edit|carti-delete', ['only' => ['index','show']]);
   //     $this->middleware('permission:carti-create', ['only' => ['create','store']]);
   //     $this->middleware('permission:carti-edit', ['only' => ['edit','update']]);
   //     $this->middleware('permission:carti-delete', ['only' => ['destroy']]);
   // }


    public function index2(){

        return Carti::all();
    }

    public function index()
    {

        $carti = Carti::latest()->paginate(5);
        return view('carti.index',compact('carti'))
            ->with('i', (request()->input('page', 1) - 1) * 5);

       // return Carti::all();
    }

    public function create()
    {
        return view('carti.create');
    }

  //  public function show(Carti $id)
  //  {
   //     return Carti::find($id);

 //   }

    public function show(Carti $carti)
    {
        return view('carti.show', compact('carti'));
    }


    public function edit(Carti $carti)
    {
        return view('carti.edit', compact('carti'));
    }



    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'titlu' => 'required',
            'autor' => 'required',
            'pret' => 'required',
            'cantitati' => 'required',
            'imagePath' => 'required'
        ]);

        Carti::create($request->all());
        return redirect()->route('carti.index')
                        ->with('success','Carte creeata cu succes');


        //$carti = Carti::create($request->all());

       // return response()->json($carti, 201);
    }

  //  public function update(Request $request, $id)
  //  {
  //      $carti = Carti::findOrFail($id);
   //     $carti->update($request->all());

   //     return $carti;
  //  }


    public function update(Request $request, Carti $carti)
    {
        request()->validate([
            'titlu' => 'required',
            'autor' => 'required',
            'pret' => 'required',
            'cantitati' => 'required',
            'imagePath' => 'required'
        ]);

        $carti->update($request->all());

        return redirect()->route('carti.index')
            ->with('success','Carte updated successfully');
    }



    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    //public function delete(Request $request, $id)
  //  {
   //     $carti = Carti::findOrFail($id);
  //      $carti->delete();

   //     return 204;
  //  }

    public function destroy(Carti $carti)
    {
        $carti->delete();

        return redirect()->route('carti.index')
            ->with('success','Carte deleted successfully');

    }


}

resources/views/carti/create.blade.php
@extends('carti.layout')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Add New Carte</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('carti.index') }}"> Back</a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('carti.store') }}" method="POST">
        @csrf

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Titlu:</strong>
                    <input type="text" name="titlu" class="form-control" placeholder="Titlu">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Autor:</strong>
                    <textarea class="form-control" style="height:50px" name="autor" placeholder="Autor"></textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>imagePath:</strong>
                    <textarea class="form-control" style="height:50px" name="imagePath" placeholder="ImagePath"></textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Pret:</strong>
                    <input type="text" name="pret" class="form-control" placeholder="Pret">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Cantitati:</strong>
                    <input type="text" name="cantitati" class="form-control" placeholder="Cantitati">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>

    </form>
@endsection

resources/views/carti/edit.blade.php
@extends('carti.layout')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Carte</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('carti.index') }}"> Back</a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('carti.update',$carti->id) }}" method="POST">
        @csrf
        @method('PUT')

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Titlu:</strong>
                    <input type="text" name="titlu" class="form-control" placeholder="Titlu">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Autor:</strong>
                    <textarea class="form-control" style="height:50px" name="autor" placeholder="Autor"></textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>imagePath:</strong>
                    <textarea class="form-control" style="height:50px" name="imagePath" placeholder="ImagePath"></textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Pret:</strong>
                    <input type="text" name="pret" class="form-control" placeholder="Pret">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Cantitati:</strong>
                    <input type="text" name="cantitati" class="form-control" placeholder="Cantitati">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>

    </form>
@endsection

resources/views/carti/index.blade.php
@extends('layouts.master')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">

            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('carti.create') }}"> Creeaza o noua carte</a>
            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Titlu</th>
            <th>Autor</th>
            <th>ImagePath</th>
            <th>Pret</th>
            <th>Cantitati</th>
            <th width="280px">Action</th>
        </tr>
        @foreach ($carti as $carte)
            <tr>
                <td>{{ ++$i }}</td>
                <td>{{ $carte->titlu }}</td>
                <td>{{ $carte->autor }}</td>
                <td>{{ $carte->imagePath}}</td>
                <td>{{ $carte->pret }}</td>
                <td>{{ $carte->cantitati }}</td>
                <td>
                    <form action="{{ route('carti.destroy',$carte->id) }}" method="POST">

                        <a class="btn btn-info" href="{{ route('carti.show',$carte->id) }}">Show</a>

                        <a class="btn btn-primary" href="{{ route('carti.edit',$carte->id) }}">Edit</a>

                        @csrf
                        @method('DELETE')

                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
        @endforeach
    </table>

    {!! $carti->links() !!}

@endsection

resources/views/carti/layout.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>CRUD</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">
</head>
<body>

<div class="container">
    @yield('content')
</div>

</body>
</html>

resources/views/carti/show.blade.php
@extends('carti.layout')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show Carte</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('carti.index') }}"> Back</a>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Titlu:</strong>
                {{ $carti->titlu }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Autor:</strong>
                {{ $carti->autor }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <img src="{{ $carti->imagePath }}" alt="..." style="max-height: 150px" class="img-responsive">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Pret:</strong>
                {{ $carti->pret }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Cantitati:</strong>
                {{ $carti->cantitati }}
            </div>
        </div>
    </div>
@endsection